name: Payment Service CI Pipeline

on:
  push:
    branches: [ main, feature/payment-service-* ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Unit tests (only *ImplTest)
        run: mvn -Dtest=**/*ImplTest test

  integration-tests:
    name: Run Integration Tests (Testcontainers)
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      TESTCONTAINERS_CHECKS_DISABLE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Integration tests (*IT)
        run: mvn -Dspring.profiles.active=test -Dtest=**/*IT verify

  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: integration-tests


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build for analysis
        run: mvn clean install -DskipTests

      - name: SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=AsonauMaksim_payment-service \
            -Dsonar.organization=asonaumaksim \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.branch.name=${GITHUB_REF_NAME}

  docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: sonar-analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Extract version from pom.xml
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Package JAR
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t zabungalilovo/payment-service:${{ env.VERSION }} .
          docker tag zabungalilovo/payment-service:${{ env.VERSION }} zabungalilovo/payment-service:latest

      - name: Push Docker image
        run: |
          docker push zabungalilovo/payment-service:${{ env.VERSION }}
          docker push zabungalilovo/payment-service:latest
